### Login

POST http://localhost:8989/users/login
Content-Type: application/json

{
  "username" : "eliott",
  "password" : "123"
}

> {%
client.global.set("token", response.body.token);
%}

### Create a post

POST http://localhost:8989/posts
Content-Type: application/json
Authorization: {{token}}

{
  "id_url": "TaAM5MovXp0",
  "text" : "Salut ça va ?"
}


### Get feed
GET http://localhost:8989/posts
Authorization: {{token}}

### Get a post
GET http://localhost:8989/posts/300
Authorization: {{token}}


### Like a post

POST http://localhost:8989/posts/1/likes
Content-Type: application/json
Authorization: {{token}}

### unlike a post

DELETE http://localhost:8989/posts/1/likes
Content-Type: application/json
Authorization: {{token}}

### GET Likes of a post

GET http://localhost:8989/posts/1/likes
Authorization: {{token}}


### Share a post

POST http://localhost:8989/posts/1/shares
Content-Type: application/json
Authorization: {{token}}

### unshare a post

DELETE http://localhost:8989/posts/1/shares
Content-Type: application/json
Authorization: {{token}}

### GET Shares of a post

GET http://localhost:8989/posts/1/shares
Authorization: {{token}}

