### GET with integrated name
GET http://localhost:8989/users/mehdi
Authorization: {{token}}

### GET with params
GET http://localhost:8989/users/email?id=10
Authorization: {{token}}


### POST with json (resend the same object)

POST http://localhost:8989/users/
Content-Type: application/json

{
  "username" : "mehdi",
  "email" : "mehdi@gmail.com",
  "password" : "azerty123"
}

### Login

POST http://localhost:8989/users/login
Content-Type: application/json

{
  "username" : "rayan",
  "password" : "M0td@"
}

> {%
client.global.set("token", response.body.token);
%}

### Register

POST http://localhost:8989/users/register
Content-Type: application/json

{
  "username": "rayan",
  "email" : "rayan@gmail.com",
  "password" : "M0tde@"
}

### Simple get
GET http://localhost:8989/users/
Authorization: {{token}}