### Register

POST http://localhost:8989/users/register
Content-Type: application/json

{
  "username": "rayan",
  "email" : "rayan@gmail.com",
  "password" : "M0tde@"
}

> {%
client.global.set("token", response.body.token);
%}

### Register

POST http://localhost:8989/users/register
Content-Type: application/json

{
  "username": "zoe",
  "email" : "zoe@gmail.com",
  "password" : "zoe"
}

> {%
client.global.set("token", response.body.token);
%}


### Login

POST http://localhost:8989/users/login
Content-Type: application/json

{
  "username" : "rayan",
  "password" : "M0tde@"
}

### Login

POST http://localhost:8989/users/login
Content-Type: application/json

{
  "username" : "zoe",
  "password" : "zoe"
}


> {%
client.global.set("token", response.body.token);
%}

### GET User connected
GET http://localhost:8989/users
Authorization: {{token}}

### Update user

PUT http://localhost:8989/users
Authorization: {{token}}
Content-Type: application/json

{
  "biography": "Je suis heureuse",
  "new_password": "zoe",
  "password": "zou"
}

### Get user by id

GET http://localhost:8989/users/1
Authorization: {{token}}

### Make user admin

PUT http://localhost:8989/users/1
Authorization: {{token}}

### Get picture of a user

GET http://localhost:8989/users/1/picture
Authorization: {{token}}
