### Login

POST http://localhost:8989/users/login
Content-Type: application/json

{
  "email" : "mehdi@gmail.com",
  "password" : "azerty123"
}

> {%
client.global.set("token", response.body.token);
%}

### Create a post

POST http://localhost:8989/posts
Content-Type: application/json
Authorization: {{token}}

{
  "id_url": "TaAM5MovXp0",
  "text" : "Aujourd'hui je mange des pommes avec Jamy"
}